Repository clone-market/market-backend, pull requests merged in 2021-06, with the labels that each got.

#2 멀티 모듈 생성 (미완)
  market-api/build.gradle
  market-common/build.gradle
  market-core/build.gradle
  settings.gradle
Labels: ⏳우선순위:상, ⚙ 설정

#3 SET #1 - 프로젝트 설정 완료
  .gitignore
  build.gradle
  market-api/build.gradle
  market-api/src/main/java/com/market/Application.java
  market-api/src/main/java/com/market/api/user/UserController.java
  market-common/build.gradle
  market-core/build.gradle
  market-core/src/main/java/com/market/common/domain/BaseTimeEntity.java
  market-core/src/main/java/com/market/config/QuerydslConfig.java
  market-core/src/main/java/com/market/member/domain/Gender.java
  market-core/src/main/java/com/market/member/domain/Member.java
  market-core/src/main/java/com/market/member/domain/MemberQueryRepository.java
  market-core/src/main/java/com/market/member/domain/MemberRepository.java
  market-core/src/main/java/com/market/member/domain/Yn.java
  market-core/src/test/java/com/market/Application.java
  market-core/src/test/java/com/market/member/domain/MemberRepositoryTests.java
Labels: ⏳우선순위:상, ⚙ 설정

#11 price 필드 추가, short_descript 필드 카멜 케이스로 수정
  market-core/src/main/java/com/market/product/entity/Product.java
Labels: ⏳우선순위:상, 🔥버그, 🧰이상 감지

#12 회원가입 관련 API 구현 완료
  .gitignore
  gradlew
  market-api/build.gradle
  market-api/src/main/java/com/market/api/user/MemberController.java
  market-api/src/main/java/com/market/api/user/UserController.java
  market-api/src/main/java/com/market/api/user/dto/findInfo/ChangePwdParam.java
  market-api/src/main/java/com/market/api/user/dto/findInfo/FindIdParam.java
  market-api/src/main/java/com/market/api/user/dto/findInfo/FindPwdParam.java
  market-api/src/main/java/com/market/api/user/dto/signUp/AuthCodeParam.java
  market-api/src/main/java/com/market/api/user/dto/signUp/CheckMode.java
  market-api/src/main/java/com/market/api/user/dto/signUp/DuplicationCheckParam.java
  market-api/src/main/java/com/market/api/user/dto/signUp/MemberEmailParam.java
  market-api/src/main/java/com/market/api/user/dto/signUp/MemberSignUpParam.java
  market-api/src/main/java/com/market/api/user/exceptionHandler/ErrorParam.java
  market-api/src/main/java/com/market/api/user/exceptionHandler/MemberApiExceptionHandler.java
  market-api/src/main/java/com/market/api/user/validator/MemberSignUpValidator.java
  market-api/src/main/resources/application-prod.yml
  market-api/src/main/resources/ehcache.xml
  market-api/src/test/java/com/market/api/user/MemberControllerTest.java
  market-core/build.gradle
  market-core/src/main/java/com/market/config/CacheConfig.java
  market-core/src/main/java/com/market/mail/dto/EmailMessageParam.java
  market-core/src/main/java/com/market/mail/service/ConsoleEmailService.java
  market-core/src/main/java/com/market/mail/service/EmailService.java
  market-core/src/main/java/com/market/mail/service/HtmlEmailService.java
  market-core/src/main/java/com/market/member/dto/AddressCreationParam.java
  market-core/src/main/java/com/market/member/dto/MemberCreationParam.java
  market-core/src/main/java/com/market/member/dto/MemberParam.java
  market-core/src/main/java/com/market/member/dto/TermsCreationParam.java
  market-core/src/main/java/com/market/member/entity/Address.java
  market-core/src/main/java/com/market/member/entity/Gender.java
  market-core/src/main/java/com/market/member/entity/Member.java
  market-core/src/main/java/com/market/member/entity/MemberTerms.java
  market-core/src/main/java/com/market/member/entity/Yn.java
  market-core/src/main/java/com/market/member/exception/EnumValidationException.java
  market-core/src/main/java/com/market/member/repository/AddressRepository.java
  market-core/src/main/java/com/market/member/repository/CustomMemberRepository.java
  market-core/src/main/java/com/market/member/repository/MemberGradeRepository.java
  market-core/src/main/java/com/market/member/repository/MemberRepository.java
  market-core/src/main/java/com/market/member/repository/MemberRepositoryImpl.java
  market-core/src/main/java/com/market/member/service/MemberService.java
  market-core/src/main/resources/ehcache.xml
  market-core/src/main/resources/templates/mail/email-form.html
  market-core/src/test/java/com/market/factory/MemberGradeFactory.java
  market-core/src/test/java/com/market/member/entity/MemberRepositoryTests.java
  market-core/src/test/java/com/market/member/service/MemberServiceTest.java
Labels: 🔨기능 개발

#16 build.gradle 설정을 통합했습니다.
  build.gradle
  market-api/build.gradle
  market-common/build.gradle
  market-core/build.gradle
  market-core/src/main/resources/application.yml
Labels: ⏳우선순위:하, ⚙ 설정

#18 스프링 시큐리티, jwt를 적용하여 토큰 발급 api를 구현했습니다.
  build.gradle
  market-api/src/main/java/com/market/api/config/PasswordConfig.java
  market-api/src/main/java/com/market/api/config/SecurityConfig.java
  market-api/src/main/java/com/market/api/security/JwtAuthenticationToken.java
  market-api/src/main/java/com/market/api/security/SkipPathRequestMatcher.java
  market-api/src/main/java/com/market/api/security/exception/AuthMethodNotSupportedException.java
  market-api/src/main/java/com/market/api/security/exception/JwtExpiredTokenException.java
  market-api/src/main/java/com/market/api/security/filter/AsyncLoginProcessingFilter.java
  market-api/src/main/java/com/market/api/security/filter/JwtTokenAuthenticationProcessingFilter.java
  market-api/src/main/java/com/market/api/security/handler/AsyncLoginAuthenticationSuccessHandler.java
  market-api/src/main/java/com/market/api/security/handler/CommonAuthenticationFailureHandler.java
  market-api/src/main/java/com/market/api/security/model/LoginRequest.java
  market-api/src/main/java/com/market/api/security/provider/AsyncAuthenticationProvider.java
  market-api/src/main/java/com/market/api/security/provider/JwtAuthenticationProvider.java
  market-api/src/main/java/com/market/api/security/service/CustomUserDetailsService.java
  market-api/src/main/java/com/market/api/security/util/JwtUtil.java
  market-api/src/main/resources/application-prod.yml
  market-api/src/main/resources/application.yml
  market-api/src/test/java/com/market/api/security/AuthenticationTest.java
  market-api/src/test/java/com/market/api/user/MemberControllerTest.java
  market-core/src/main/java/com/market/member/dto/MemberParam.java
  market-core/src/main/java/com/market/member/entity/Grade.java
  market-core/src/main/java/com/market/member/entity/Member.java
  market-core/src/main/java/com/market/member/entity/MemberGrade.java
  market-core/src/main/java/com/market/member/repository/MemberGradeRepository.java
  market-core/src/main/java/com/market/member/service/MemberService.java
  market-core/src/test/java/com/market/factory/MemberGradeFactory.java
  market-core/src/test/java/com/market/member/service/MemberServiceTest.java
Labels: ⏳우선순위:상, 🔨 기능 개발

#20 cacheManger 싱글톤으로 변경
  build.gradle
  market-core/src/main/java/com/market/config/CacheConfig.java
Labels: ⏳ 우선순위:상, 🔥 버그

#24 회원 API 수정, Security설정 완료
  build.gradle
  market-api/src/main/java/com/market/api/config/SecurityConfig.java
  market-api/src/main/java/com/market/api/user/MemberController.java
  market-common/src/main/java/com/market/config/PasswordConfig.java
  market-core/src/main/java/com/market/member/service/MemberService.java
Labels: ⏳ 우선순위:상, ⚙ 설정
